"""Write backend/app/knowledge/concepts.json (135 SEE P/C/B nodes). Run from repo root:

    python backend/scripts/build_concepts_json.py
"""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "app" / "knowledge" / "concepts.json"


def node(nid: str, subject: str, name: str, chapter: str, aliases: list[str]) -> dict:
    return {
        "id": nid,
        "subject": subject,
        "name": name,
        "chapter": chapter,
        "aliases": aliases,
    }


PHYSICS = [
    node("phy_measurement", "Physics", "Measurement", "Measurement", ["measure", "reading", "instrument"]),
    node("phy_si_units", "Physics", "SI units", "Measurement", ["si", "metre", "kilogram", "second"]),
    node("phy_scalars", "Physics", "Scalars", "Force and motion", ["scalar quantity"]),
    node("phy_vectors", "Physics", "Vectors", "Force and motion", ["vector quantity", "direction"]),
    node("phy_distance_displacement", "Physics", "Distance and displacement", "Force and motion", ["displacement", "distance"]),
    node("phy_speed", "Physics", "Speed", "Force and motion", ["how fast"]),
    node("phy_velocity", "Physics", "Velocity", "Force and motion", ["velocity"]),
    node("phy_acceleration", "Physics", "Acceleration", "Force and motion", ["accelerate", "decelerate"]),
    node("phy_motion_graphs", "Physics", "Motion graphs", "Force and motion", ["distance time", "velocity time", "graph of motion"]),
    node("phy_force", "Physics", "Force", "Force and motion", ["push", "pull", "newton"]),
    node("phy_newton_first", "Physics", "Newton's first law", "Force and motion", ["inertia", "uniform motion", "first law"]),
    node("phy_newton_second", "Physics", "Newton's second law", "Force and motion", ["f=ma", "second law"]),
    node("phy_newton_third", "Physics", "Newton's third law", "Force and motion", ["action reaction", "third law"]),
    node("phy_mass", "Physics", "Mass", "Force and motion", ["amount of matter"]),
    node("phy_weight", "Physics", "Weight", "Force and motion", ["gravity on a mass"]),
    node("phy_friction", "Physics", "Friction", "Force and motion", ["resist motion", "rough"]),
    node("phy_momentum", "Physics", "Momentum", "Force and motion", ["mass times velocity"]),
    node("phy_pressure", "Physics", "Pressure", "Pressure", ["force over area", "pascal"]),
    node("phy_atmospheric_pressure", "Physics", "Atmospheric pressure", "Pressure", ["air pressure", "barometer"]),
    node("phy_liquid_pressure", "Physics", "Pressure in liquids", "Pressure", ["depth", "hydraulic"]),
    node("phy_density", "Physics", "Density", "Pressure", ["mass over volume", "dense"]),
    node("phy_buoyancy", "Physics", "Buoyancy", "Pressure", ["upthrust", "float", "sink", "ice float"]),
    node("phy_archimedes", "Physics", "Archimedes' principle", "Pressure", ["displaced liquid"]),
    node("phy_work", "Physics", "Work", "Work, energy and power", ["force times distance"]),
    node("phy_energy", "Physics", "Energy", "Work, energy and power", ["ability to do work"]),
    node("phy_kinetic_energy", "Physics", "Kinetic energy", "Work, energy and power", ["moving energy"]),
    node("phy_potential_energy", "Physics", "Potential energy", "Work, energy and power", ["stored energy", "gravitational potential"]),
    node("phy_conservation_energy", "Physics", "Conservation of energy", "Work, energy and power", ["energy cannot be created"]),
    node("phy_power", "Physics", "Power", "Work, energy and power", ["work per time", "watt"]),
    node("phy_simple_machines", "Physics", "Simple machines", "Work, energy and power", ["lever", "pulley", "inclined plane"]),
    node("phy_heat", "Physics", "Heat", "Heat", ["thermal energy"]),
    node("phy_temperature", "Physics", "Temperature", "Heat", ["hot cold", "thermometer", "celsius"]),
    node("phy_thermal_expansion", "Physics", "Thermal expansion", "Heat", ["expand on heating"]),
    node("phy_heat_transfer", "Physics", "Heat transfer", "Heat", ["conduction", "convection", "radiation"]),
    node("phy_wave", "Physics", "Waves", "Wave and sound", ["wavelength", "frequency", "amplitude"]),
    node("phy_sound", "Physics", "Sound", "Wave and sound", ["vibration", "echo", "loudness", "pitch"]),
    node("phy_light", "Physics", "Light", "Light", ["ray", "luminous"]),
    node("phy_reflection", "Physics", "Reflection of light", "Light", ["mirror", "incident ray"]),
    node("phy_refraction", "Physics", "Refraction of light", "Light", ["bend", "pencil in water", "snell"]),
    node("phy_lenses", "Physics", "Lenses", "Light", ["convex", "concave", "focal"]),
    node("phy_human_eye", "Physics", "Human eye", "Light", ["retina", "lens of eye", "myopia"]),
    node("phy_current", "Physics", "Electric current", "Current electricity and magnetism", ["ampere", "flow of charge"]),
    node("phy_voltage", "Physics", "Potential difference", "Current electricity and magnetism", ["voltage", "volt"]),
    node("phy_resistance", "Physics", "Resistance", "Current electricity and magnetism", ["ohm", "resistor"]),
    node("phy_ohms_law", "Physics", "Ohm's law", "Current electricity and magnetism", ["v=ir", "ohms law"]),
    node("phy_circuits", "Physics", "Series and parallel circuits", "Current electricity and magnetism", ["series", "parallel"]),
    node("phy_magnetism", "Physics", "Magnetism", "Current electricity and magnetism", ["magnet", "north pole", "field lines"]),
    node("phy_electromagnet", "Physics", "Electromagnet", "Current electricity and magnetism", ["coil", "solenoid"]),
    node("phy_earth_gravity", "Physics", "Gravity", "Earth in space", ["g", "attract"]),
    node("phy_solar_system", "Physics", "Earth and solar system", "Earth in space", ["planet", "orbit", "sun"]),
]

_DROP_PHYSICS = {
    "phy_liquid_pressure",
    "phy_simple_machines",
    "phy_thermal_expansion",
    "phy_earth_gravity",
    "phy_solar_system",
}
PHYSICS = [item for item in PHYSICS if item["id"] not in _DROP_PHYSICS]
assert len(PHYSICS) == 45, len(PHYSICS)

CHEMISTRY = [
    node("che_matter", "Chemistry", "Matter", "Classification of materials", ["stuff", "material"]),
    node("che_states", "Chemistry", "States of matter", "Classification of materials", ["solid", "liquid", "gas"]),
    node("che_element", "Chemistry", "Element", "Classification of materials", ["pure element"]),
    node("che_compound", "Chemistry", "Compound", "Classification of materials", ["chemical compound"]),
    node("che_mixture", "Chemistry", "Mixture", "Classification of materials", ["mix", "alloy"]),
    node("che_solution", "Chemistry", "Solution", "Classification of materials", ["solute", "solvent", "dissolve"]),
    node("che_atom", "Chemistry", "Atom", "Atomic structure", ["smallest particle of element"]),
    node("che_molecule", "Chemistry", "Molecule", "Atomic structure", ["group of atoms"]),
    node("che_proton", "Chemistry", "Proton", "Atomic structure", ["positive nucleus"]),
    node("che_neutron", "Chemistry", "Neutron", "Atomic structure", ["neutral nucleus"]),
    node("che_electron", "Chemistry", "Electron", "Atomic structure", ["negative", "orbit"]),
    node("che_atomic_number", "Chemistry", "Atomic number", "Atomic structure", ["proton number", "z"]),
    node("che_mass_number", "Chemistry", "Mass number", "Atomic structure", ["nucleon", "a"]),
    node("che_electronic_config", "Chemistry", "Electronic configuration", "Atomic structure", ["shells", "2,8,8"]),
    node("che_valency", "Chemistry", "Valency", "Atomic structure", ["combining capacity"]),
    node("che_periodic_table", "Chemistry", "Periodic table", "Periodic table", ["groups", "periods", "mendeleev"]),
    node("che_metals", "Chemistry", "Metals", "Periodic table", ["metallic", "lustre"]),
    node("che_nonmetals", "Chemistry", "Non-metals", "Periodic table", ["nonmetal"]),
    node("che_reactivity", "Chemistry", "Metal reactivity", "Metals", ["reactivity series"]),
    node("che_ionic_bond", "Chemistry", "Ionic bond", "Chemical bonding", ["transfer electrons", "ion"]),
    node("che_covalent_bond", "Chemistry", "Covalent bond", "Chemical bonding", ["share electrons"]),
    node("che_formula", "Chemistry", "Chemical formula", "Language of chemistry", ["h2o", "co2", "formula"]),
    node("che_equation", "Chemistry", "Chemical equation", "Language of chemistry", ["reaction equation"]),
    node("che_balancing", "Chemistry", "Balancing equations", "Language of chemistry", ["balance", "coefficients"]),
    node("che_conservation_mass", "Chemistry", "Conservation of mass", "Language of chemistry", ["mass conserved"]),
    node("che_acid", "Chemistry", "Acids", "Acid, base and salt", ["sour", "h+"]),
    node("che_base", "Chemistry", "Bases", "Acid, base and salt", ["bitter", "oh-", "alkali"]),
    node("che_salt", "Chemistry", "Salts", "Acid, base and salt", ["nacl", "neutralisation product"]),
    node("che_ph", "Chemistry", "pH", "Acid, base and salt", ["ph scale"]),
    node("che_indicator", "Chemistry", "Indicators", "Acid, base and salt", ["litmus", "phenolphthalein"]),
    node("che_neutralization", "Chemistry", "Neutralisation", "Acid, base and salt", ["acid plus base"]),
    node("che_oxidation", "Chemistry", "Oxidation", "Chemical reaction", ["gain oxygen", "lose electrons"]),
    node("che_reduction", "Chemistry", "Reduction", "Chemical reaction", ["lose oxygen"]),
    node("che_rusting", "Chemistry", "Rusting", "Chemical reaction", ["iron rust", "corrosion"]),
    node("che_water", "Chemistry", "Water", "Water", ["h2o", "universal solvent"]),
    node("che_hard_water", "Chemistry", "Hard water", "Water", ["calcium", "lather"]),
    node("che_air", "Chemistry", "Air", "Some gases", ["atmosphere mixture"]),
    node("che_oxygen", "Chemistry", "Oxygen", "Some gases", ["o2", "supports burning"]),
    node("che_carbon_dioxide", "Chemistry", "Carbon dioxide", "Some gases", ["co2", "limewater"]),
    node("che_nitrogen", "Chemistry", "Nitrogen", "Some gases", ["n2"]),
    node("che_hydrogen", "Chemistry", "Hydrogen", "Some gases", ["h2", "pop test"]),
    node("che_carbon", "Chemistry", "Carbon", "Carbon and its compounds", ["allotrope", "diamond", "graphite"]),
    node("che_hydrocarbon", "Chemistry", "Hydrocarbons", "Carbon and its compounds", ["alkane", "methane"]),
    node("che_polymer", "Chemistry", "Polymers", "Carbon and its compounds", ["plastic", "polymerisation"]),
    node("che_fertilizer", "Chemistry", "Fertilisers", "Applied chemistry", ["npk", "urea"]),
    node("che_pesticide", "Chemistry", "Pesticides", "Applied chemistry", ["insecticide"]),
    node("che_lab_safety", "Chemistry", "Laboratory safety", "Laboratory", ["hazards", "bunsen"]),
    node("che_endothermic", "Chemistry", "Endothermic and exothermic", "Chemical reaction", ["heat given out", "heat taken in"]),
    node("che_rate", "Chemistry", "Rate of reaction", "Chemical reaction", ["catalyst", "faster reaction"]),
    node("che_electrolysis", "Chemistry", "Electrolysis", "Chemical reaction", ["electrolyte", "ions move"]),
]

assert len(CHEMISTRY) == 50, len(CHEMISTRY)

BIOLOGY = [
    node("bio_cell", "Biology", "Cell", "Cell biology", ["basic unit of life"]),
    node("bio_organelle", "Biology", "Cell organelles", "Cell biology", ["mitochondria", "nucleus", "chloroplast organelle"]),
    node("bio_plant_cell", "Biology", "Plant cell", "Cell biology", ["cell wall", "vacuole"]),
    node("bio_animal_cell", "Biology", "Animal cell", "Cell biology", ["no cell wall"]),
    node("bio_tissue", "Biology", "Tissue", "Organisation of life", ["group of cells"]),
    node("bio_organ", "Biology", "Organ", "Organisation of life", ["heart", "leaf as organ"]),
    node("bio_organ_system", "Biology", "Organ system", "Organisation of life", ["digestive system"]),
    node("bio_photosynthesis", "Biology", "Photosynthesis", "Life process in plants", ["make food", "chlorophyll", "glucose from light"]),
    node("bio_transpiration", "Biology", "Transpiration", "Life process in plants", ["water loss stomata"]),
    node("bio_tropism", "Biology", "Tropism", "Life process in plants", ["phototropism", "geotropism"]),
    node("bio_flower", "Biology", "Flower", "Life process in plants", ["petal", "stamen", "pistil"]),
    node("bio_seed", "Biology", "Seed", "Life process in plants", ["embryo plant"]),
    node("bio_germination", "Biology", "Germination", "Life process in plants", ["seed grows"]),
    node("bio_digestion", "Biology", "Digestion", "Life process in animals", ["stomach", "enzyme food"]),
    node("bio_respiration", "Biology", "Respiration", "Life process in animals", ["breathing", "oxygen glucose"]),
    node("bio_circulation", "Biology", "Circulation", "Life process in animals", ["blood", "heart pump"]),
    node("bio_excretion", "Biology", "Excretion", "Life process in animals", ["kidney", "urea"]),
    node("bio_nervous", "Biology", "Nervous system", "Life process in animals", ["brain", "neuron", "reflex"]),
    node("bio_reproduction", "Biology", "Reproduction", "Reproduction", ["offspring"]),
    node("bio_mitosis", "Biology", "Mitosis", "Reproduction", ["cell division body"]),
    node("bio_meiosis", "Biology", "Meiosis", "Reproduction", ["gamete", "half chromosomes"]),
    node("bio_dna", "Biology", "DNA", "Heredity", ["genetic material", "double helix"]),
    node("bio_chromosome", "Biology", "Chromosome", "Heredity", ["chromatin"]),
    node("bio_heredity", "Biology", "Heredity", "Heredity", ["inherited", "traits"]),
    node("bio_microorganism", "Biology", "Microorganisms", "Microbiology", ["microbe"]),
    node("bio_bacteria", "Biology", "Bacteria", "Microbiology", ["bacterial"]),
    node("bio_virus", "Biology", "Virus", "Microbiology", ["viral"]),
    node("bio_fungi", "Biology", "Fungi", "Microbiology", ["fungus", "yeast"]),
    node("bio_pathogen", "Biology", "Pathogen", "Health", ["disease causing"]),
    node("bio_immunity", "Biology", "Immunity", "Health", ["immune", "white blood cell"]),
    node("bio_vaccine", "Biology", "Vaccine", "Health", ["immunisation", "vaccination"]),
    node("bio_ecosystem", "Biology", "Ecosystem", "Environment", ["habitat community"]),
    node("bio_food_chain", "Biology", "Food chain", "Environment", ["producer consumer"]),
    node("bio_food_web", "Biology", "Food web", "Environment", ["linked food chains"]),
    node("bio_biodiversity", "Biology", "Biodiversity", "Environment", ["variety of life"]),
    node("bio_conservation", "Biology", "Conservation", "Environment", ["protect species"]),
    node("bio_pollution", "Biology", "Pollution", "Environment", ["air water soil pollution"]),
    node("bio_classification", "Biology", "Classification of organisms", "Diversity", ["kingdom", "species"]),
    node("bio_human_health", "Biology", "Human health", "Health", ["hygiene", "balanced diet"]),
    node("bio_hormones_plant", "Biology", "Plant hormones", "Life process in plants", ["auxin"]),
]

assert len(BIOLOGY) == 40, len(BIOLOGY)

EDGES = [
    ("phy_measurement", "phy_si_units"),
    ("phy_scalars", "phy_vectors"),
    ("phy_distance_displacement", "phy_speed"),
    ("phy_speed", "phy_velocity"),
    ("phy_velocity", "phy_acceleration"),
    ("phy_acceleration", "phy_motion_graphs"),
    ("phy_force", "phy_newton_first"),
    ("phy_newton_first", "phy_newton_second"),
    ("phy_newton_second", "phy_newton_third"),
    ("phy_mass", "phy_weight"),
    ("phy_force", "phy_friction"),
    ("phy_mass", "phy_momentum"),
    ("phy_force", "phy_pressure"),
    ("phy_pressure", "phy_atmospheric_pressure"),
    ("phy_pressure", "phy_liquid_pressure"),
    ("phy_mass", "phy_density"),
    ("phy_density", "phy_buoyancy"),
    ("phy_buoyancy", "phy_archimedes"),
    ("phy_force", "phy_work"),
    ("phy_work", "phy_energy"),
    ("phy_energy", "phy_kinetic_energy"),
    ("phy_energy", "phy_potential_energy"),
    ("phy_energy", "phy_conservation_energy"),
    ("phy_work", "phy_power"),
    ("phy_work", "phy_simple_machines"),
    ("phy_heat", "phy_temperature"),
    ("phy_temperature", "phy_thermal_expansion"),
    ("phy_heat", "phy_heat_transfer"),
    ("phy_wave", "phy_sound"),
    ("phy_light", "phy_reflection"),
    ("phy_light", "phy_refraction"),
    ("phy_refraction", "phy_lenses"),
    ("phy_lenses", "phy_human_eye"),
    ("phy_current", "phy_voltage"),
    ("phy_voltage", "phy_resistance"),
    ("phy_resistance", "phy_ohms_law"),
    ("phy_ohms_law", "phy_circuits"),
    ("phy_magnetism", "phy_electromagnet"),
    ("che_matter", "che_states"),
    ("che_element", "che_compound"),
    ("che_compound", "che_mixture"),
    ("che_mixture", "che_solution"),
    ("che_atom", "che_molecule"),
    ("che_atom", "che_proton"),
    ("che_atom", "che_neutron"),
    ("che_atom", "che_electron"),
    ("che_proton", "che_atomic_number"),
    ("che_proton", "che_mass_number"),
    ("che_electron", "che_electronic_config"),
    ("che_electronic_config", "che_valency"),
    ("che_element", "che_periodic_table"),
    ("che_periodic_table", "che_metals"),
    ("che_periodic_table", "che_nonmetals"),
    ("che_metals", "che_reactivity"),
    ("che_valency", "che_ionic_bond"),
    ("che_valency", "che_covalent_bond"),
    ("che_formula", "che_equation"),
    ("che_equation", "che_balancing"),
    ("che_balancing", "che_conservation_mass"),
    ("che_acid", "che_base"),
    ("che_acid", "che_ph"),
    ("che_ph", "che_indicator"),
    ("che_acid", "che_neutralization"),
    ("che_base", "che_salt"),
    ("che_oxidation", "che_reduction"),
    ("che_oxidation", "che_rusting"),
    ("che_water", "che_hard_water"),
    ("che_air", "che_oxygen"),
    ("che_air", "che_carbon_dioxide"),
    ("che_air", "che_nitrogen"),
    ("che_carbon", "che_hydrocarbon"),
    ("che_hydrocarbon", "che_polymer"),
    ("che_equation", "che_endothermic"),
    ("che_equation", "che_rate"),
    ("bio_cell", "bio_organelle"),
    ("bio_cell", "bio_plant_cell"),
    ("bio_cell", "bio_animal_cell"),
    ("bio_cell", "bio_tissue"),
    ("bio_tissue", "bio_organ"),
    ("bio_organ", "bio_organ_system"),
    ("bio_plant_cell", "bio_photosynthesis"),
    ("bio_photosynthesis", "bio_transpiration"),
    ("bio_flower", "bio_seed"),
    ("bio_seed", "bio_germination"),
    ("bio_organ_system", "bio_digestion"),
    ("bio_organ_system", "bio_respiration"),
    ("bio_organ_system", "bio_circulation"),
    ("bio_organ_system", "bio_excretion"),
    ("bio_organ_system", "bio_nervous"),
    ("bio_cell", "bio_mitosis"),
    ("bio_mitosis", "bio_meiosis"),
    ("bio_meiosis", "bio_reproduction"),
    ("bio_dna", "bio_chromosome"),
    ("bio_chromosome", "bio_heredity"),
    ("bio_microorganism", "bio_bacteria"),
    ("bio_microorganism", "bio_virus"),
    ("bio_microorganism", "bio_fungi"),
    ("bio_pathogen", "bio_immunity"),
    ("bio_immunity", "bio_vaccine"),
    ("bio_ecosystem", "bio_food_chain"),
    ("bio_food_chain", "bio_food_web"),
    ("bio_biodiversity", "bio_conservation"),
]


def main() -> None:
    nodes = PHYSICS + CHEMISTRY + BIOLOGY
    by_id = {n["id"]: n for n in nodes}
    assert len(nodes) == 135, len(nodes)
    assert len(by_id) == 135
    edges = [{"from": a, "to": b} for a, b in EDGES if a in by_id and b in by_id]
    for edge in edges:
        assert edge["from"] in by_id
        assert edge["to"] in by_id

    payload = {
        "version": 1,
        "title": "SEE Class 10 Science concept graph (Physics 45, Chemistry 50, Biology 40)",
        "source": "CDC/NEB-aligned concept list for Clariq FYP Objective 4. Prerequisite edges are a working set pending teacher kappa.",
        "counts": {
            "Physics": sum(1 for n in nodes if n["subject"] == "Physics"),
            "Chemistry": sum(1 for n in nodes if n["subject"] == "Chemistry"),
            "Biology": sum(1 for n in nodes if n["subject"] == "Biology"),
            "edges": len(edges),
        },
        "nodes": nodes,
        "edges": edges,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({payload['counts']})")


if __name__ == "__main__":
    main()
